/* ============================================
   HOMEHUT — PRODUCT DATA & STORE STATE
   Smart. Modern. Efficient.
   ============================================ */

const HOMEHUT = {
  store: {
    name: 'HomeHut',
    tagline: 'Smart. Modern. Efficient.',
    currency: '₹',
    currencyCode: 'INR',
    freeShippingThreshold: 999,
    email: 'homehut09@gmail.com',
    phone: '+91 8983347437',
    whatsapp: 'https://wa.me/918983347437',
    instagram: 'https://www.instagram.com/homehut.in',
    instagramHandle: '@homehut.in',
  },
  categories: [
    {
      id: 'kitchen-appliances',
      name: 'Kitchen Appliances',
      slug: 'kitchen-appliances',
      description: 'Smart tools for your kitchen — faster cooking, better results',
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 2h8l2 8H6l2-8z"/><path d="M6 10v8a4 4 0 004 4h4a4 4 0 004-4v-8"/><line x1="12" y1="14" x2="12" y2="18"/></svg>`,
      image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=400&fit=crop'
    },
    {
      id: 'home-appliances',
      name: 'Home Appliances',
      slug: 'home-appliances',
      description: 'Efficient appliances for every room in your home',
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>`,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop'
    },
    {
      id: 'useful-accessories',
      name: 'Useful Accessories',
      slug: 'useful-accessories',
      description: 'Everyday accessories that make life simpler and more organized',
      icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>`,
      image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=400&fit=crop'
    }
  ],
  products: [
    { id: 'prod-001', title: 'ProBlend 3000 Smart Blender', handle: 'problend-3000-smart-blender', category: 'kitchen-appliances', description: 'The ProBlend 3000 features a powerful 1200W motor with 10 speed settings and smart auto-blend technology.', images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1585237672814-8922cde71f24?w=600&h=600&fit=crop&auto=format'], price: 4999, compareAtPrice: 7499, sku: 'HH-KA-001', rating: 4.8, reviewCount: 234, isBestseller: true, isNew: false, isSale: true, inStock: true, inventory: 42, tags: ['blender', 'smart', 'bestseller', 'kitchen'], variants: [{ color: 'Forest Green', colorHex: '#3A6B4A', inStock: true }, { color: 'Cream White', colorHex: '#F4F2EC', inStock: true }], features: ['1200W Motor', 'Smart Auto-Blend', 'BPA-Free Tritan Jar', '10 Speed Settings'], specifications: { wattage: '1200W', capacity: '1.5L', warranty: '2 Years' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-002', title: 'AeroFry Pro 5.5L Air Fryer', handle: 'aerofry-pro-55l-air-fryer', category: 'kitchen-appliances', description: 'Cook healthier meals with 95% less oil. The AeroFry Pro features rapid air circulation technology and 8 preset programs.', images: ['https://images.unsplash.com/photo-1648126809006-1eb2ebef488f?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1626509653291-18d9a934b9db?w=600&h=600&fit=crop&auto=format'], price: 6499, compareAtPrice: 9999, sku: 'HH-KA-002', rating: 4.7, reviewCount: 189, isBestseller: true, isNew: false, isSale: true, inStock: true, inventory: 28, tags: ['air fryer', 'healthy', 'bestseller', 'kitchen'], variants: [{ color: 'Matte Black', colorHex: '#2C2C2C', inStock: true }], features: ['5.5L Capacity', '8 Preset Programs', '95% Less Oil', 'Dishwasher-Safe Basket'], specifications: { wattage: '1700W', capacity: '5.5L', warranty: '2 Years' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-003', title: 'BrewMaster Elite Coffee Maker', handle: 'brewmaster-elite-coffee-maker', category: 'kitchen-appliances', description: 'Wake up to perfectly brewed coffee every morning with programmable brewing and thermal carafe.', images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop&auto=format'], price: 3499, compareAtPrice: 4999, sku: 'HH-KA-003', rating: 4.8, reviewCount: 156, isBestseller: false, isNew: true, isSale: true, inStock: true, inventory: 55, tags: ['coffee maker', 'programmable', 'new', 'kitchen'], variants: [{ color: 'Stainless Steel', colorHex: '#8C8C8C', inStock: true }], features: ['Programmable Timer', 'Thermal Carafe', 'Adjustable Strength', '12-Cup Capacity'], specifications: { wattage: '1000W', capacity: '1.5L', warranty: '1 Year' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-004', title: 'SmartBreeze Tower Fan', handle: 'smartbreeze-tower-fan', category: 'home-appliances', description: 'Powerful yet whisper-quiet tower fan with 3 speed settings and 90° oscillation.', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop&auto=format'], price: 3999, compareAtPrice: 5999, sku: 'HH-HA-001', rating: 4.8, reviewCount: 312, isBestseller: true, isNew: false, isSale: true, inStock: true, inventory: 18, tags: ['fan', 'tower fan', 'home', 'bestseller'], variants: [{ color: 'White', colorHex: '#F4F2EC', inStock: true }], features: ['3 Speed Settings', '90° Oscillation', '8-Hour Timer', 'Ultra-Quiet'], specifications: { wattage: '50W', warranty: '2 Years' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-005', title: 'FreshSeal Vacuum Storage Set', handle: 'freshseal-vacuum-storage-set', category: 'useful-accessories', description: 'Keep food fresher for up to 5x longer with vacuum-sealed storage containers. BPA-free, set of 6.', images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=600&fit=crop&auto=format'], price: 1999, compareAtPrice: 3499, sku: 'HH-UA-001', rating: 4.7, reviewCount: 98, isBestseller: false, isNew: true, isSale: true, inStock: true, inventory: 73, tags: ['storage', 'vacuum seal', 'new', 'accessories'], variants: [{ color: 'Clear', colorHex: '#E8E8E8', inStock: true }], features: ['Vacuum-Sealed', 'BPA-Free', 'Stackable', '6-Piece Set'], specifications: { material: 'BPA-Free Tritan', warranty: '1 Year' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-006', title: 'TurboMix Hand Blender 800W', handle: 'turbomix-hand-blender-800w', category: 'kitchen-appliances', description: 'Versatile 4-in-1 hand blender with whisk, chopper, and measuring cup attachments.', images: ['https://images.unsplash.com/photo-1585237672814-8922cde71f24?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=600&fit=crop&auto=format'], price: 2499, compareAtPrice: 3999, sku: 'HH-KA-004', rating: 4.5, reviewCount: 145, isBestseller: false, isNew: false, isSale: true, inStock: true, inventory: 60, tags: ['hand blender', 'versatile', 'kitchen'], variants: [{ color: 'Silver', colorHex: '#C0C0C0', inStock: true }], features: ['800W Motor', '4-in-1 Attachments', 'Variable Speed', 'Turbo Boost'], specifications: { wattage: '800W', warranty: '2 Years' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-007', title: 'PureGlow LED Desk Lamp', handle: 'pureglow-led-desk-lamp', category: 'home-appliances', description: 'Modern LED desk lamp with 5 brightness levels, 3 color temperatures, and USB charging port.', images: ['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&h=600&fit=crop&auto=format'], price: 2299, compareAtPrice: 3499, sku: 'HH-HA-002', rating: 4.7, reviewCount: 87, isBestseller: false, isNew: true, isSale: true, inStock: true, inventory: 45, tags: ['lamp', 'LED', 'desk', 'home', 'new'], variants: [{ color: 'White', colorHex: '#F4F2EC', inStock: true }], features: ['5 Brightness Levels', '3 Color Temps', 'USB Charging', 'Flexible Gooseneck'], specifications: { wattage: '12W', warranty: '1 Year' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-008', title: 'ZenPour Pour-Over Coffee Kit', handle: 'zenpour-pour-over-coffee-kit', category: 'kitchen-appliances', description: 'Elegant pour-over kit with borosilicate glass dripper, gooseneck kettle, reusable filter and digital scale.', images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop&auto=format'], price: 2799, compareAtPrice: null, sku: 'HH-KA-005', rating: 4.9, reviewCount: 67, isBestseller: false, isNew: true, isSale: false, inStock: true, inventory: 30, tags: ['pour-over', 'artisan', 'coffee kit', 'new', 'kitchen'], variants: [], features: ['Borosilicate Glass', 'Gooseneck Kettle', 'Reusable Filter', 'Digital Scale'], specifications: { material: 'Borosilicate Glass', warranty: '1 Year' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-009', title: 'CableNest Pro Organizer Set', handle: 'cablenest-pro-organizer-set', category: 'useful-accessories', description: 'Premium cable organizer set with cable clips, cord sleeves, and charging station holder.', images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop&auto=format'], price: 1499, compareAtPrice: 2499, sku: 'HH-UA-002', rating: 4.8, reviewCount: 203, isBestseller: true, isNew: false, isSale: true, inStock: true, inventory: 5, tags: ['organizer', 'cable', 'desk', 'accessories', 'bestseller'], variants: [], features: ['Recycled Silicone', 'Bamboo Base', 'Universal Fit', '12-Piece Set'], specifications: { material: 'Recycled Silicone + Bamboo', warranty: '1 Year' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' },
    { id: 'prod-010', title: 'StackPro Bamboo Organizer Set', handle: 'stackpro-bamboo-organizer-set', category: 'useful-accessories', description: 'Sustainable bamboo organizers with spice rack, utensil holder, and tiered shelf.', images: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&h=600&fit=crop&auto=format', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop&auto=format'], price: 2999, compareAtPrice: 3999, sku: 'HH-UA-003', rating: 4.5, reviewCount: 76, isBestseller: false, isNew: false, isSale: true, inStock: true, inventory: 38, tags: ['bamboo', 'organizer', 'eco-friendly', 'sustainable', 'accessories'], variants: [], features: ['100% Bamboo', '3-Piece Set', 'Eco-Friendly', 'Easy Assembly'], specifications: { material: '100% Natural Bamboo', warranty: '1 Year' }, shippingInfo: 'Delivered in 5–6 Business Days across India.', returnPolicy: 'All sales are final.' }
  ],
  testimonials: [
    { id: 1, name: 'Priya Sharma', location: 'Mumbai', rating: 4.8, text: 'Bought the chopper last month and honestly it\'s saved me so much time every morning. Delivery in 5 days, product is exactly as shown. Very happy!', product: 'ProBlend 3000 Smart Blender', badge: '✅ Verified Buyer', date: '2 weeks ago' },
    { id: 2, name: 'Rahul Nair', location: 'Bangalore', rating: 4.7, text: 'Quality is top-notch. Using it daily for making smoothies. Feels premium. HomeHut pe trust kar sakte ho!', product: 'TurboMix Hand Blender 800W', badge: '✅ Verified Buyer', date: '3 weeks ago' },
    { id: 3, name: 'Sneha Patel', location: 'Ahmedabad', rating: 4.9, text: 'Ekdum mast product hai! My husband loves the coffee maker. Already recommended to 3 friends.', product: 'BrewMaster Elite Coffee Maker', badge: '✅ Verified Buyer', date: '1 month ago' },
    { id: 4, name: 'Arjun Mehta', location: 'Delhi', rating: 4.8, text: 'Got the table fan — powerful, quiet, and looks so sleek in my room. Worth every rupee.', product: 'SmartBreeze Tower Fan', badge: '✅ Verified Buyer', date: '2 weeks ago' },
    { id: 5, name: 'Divya Kulkarni', location: 'Pune', rating: 4.7, text: 'Packaging was excellent, product delivered in 6 days. Works perfectly. Will definitely order again.', product: 'PureGlow LED Desk Lamp', badge: '✅ Verified Buyer', date: '1 month ago' },
    { id: 6, name: 'Kavya Iyer', location: 'Chennai', rating: 4.9, text: 'The cable organizer set is just what I needed. My desk looks so clean now haha. Great quality!', product: 'CableNest Pro Organizer Set', badge: '✅ Verified Buyer', date: '3 weeks ago' },
    { id: 7, name: 'Rohan Gupta', location: 'Jaipur', rating: 4.8, text: 'Amazing product, amazing price. HomeHut is now my go-to for home stuff. Fast delivery too!', product: 'FreshSeal Vacuum Storage Set', badge: '✅ Verified Buyer', date: '1 week ago' },
    { id: 8, name: 'Nandini Rao', location: 'Hyderabad', rating: 4.7, text: 'Air fryer changed my life! I cook so many things now without oil. Kids love the fries. Thank you HomeHut!', product: 'AeroFry Pro 5.5L Air Fryer', badge: '✅ Verified Buyer', date: '2 months ago' }
  ],
  socialProofNames: ['Aarav', 'Priya', 'Rohit', 'Sneha', 'Vikram', 'Anjali', 'Kabir', 'Pooja', 'Arjun', 'Neha', 'Siddharth', 'Divya', 'Yash', 'Meera', 'Ravi', 'Ishaan', 'Swati', 'Karan', 'Nandini', 'Tarun', 'Kavya', 'Aditya', 'Shreya', 'Manish', 'Tanya', 'Deepak', 'Komal', 'Nikhil', 'Simran', 'Amit'],
  socialProofCities: ['Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Hyderabad', 'Chennai', 'Jaipur', 'Ahmedabad', 'Kolkata', 'Surat', 'Lucknow', 'Chandigarh'],
  returnPolicy: 'All sales at HomeHut are final. We currently do not accept returns or exchanges once an order has been placed and confirmed.',
  deliveryTimeline: 'Delivered in 5–6 Business Days',
};

window.HOMEHUT = HOMEHUT;
